development:
  adapter: mysql
  encoding: utf8  
  database: testApp_dev
  pool: 5
  username: root
  password: mohan143
  port: 3306
  host: 127.0.0.1
test:
  adapter: mysql
  encoding: utf8  
  database: testApp_test
  pool: 5
  username: root
  password: mohan143
  port: 3306
  host: 127.0.0.1

production:
  adapter: mysql
  encoding: utf8
  database: testApp_pro
  pool: 5
  username: root
  password: mohan143
  port: 3306
  host: 127.0.0.1